name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    - name: Create checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
    
    - name: Build test
      run: mvn --batch-mode -DskipTests package
   
    - name: Run test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      
  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
        
    - name: Build report test
      uses: dorny/test-report@v3
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
